USE [master]
GO

/****** Object:  Database [EVALUACION]    Script Date: 11/09/2020 20:59:13 ******/
DROP DATABASE [EVALUACION]
GO

/****** Object:  Database [EVALUACION]    Script Date: 11/09/2020 20:59:13 ******/
CREATE DATABASE [EVALUACION]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EVALUACION', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EVALUACION.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EVALUACION_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EVALUACION_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EVALUACION].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EVALUACION] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EVALUACION] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EVALUACION] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EVALUACION] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EVALUACION] SET ARITHABORT OFF 
GO

ALTER DATABASE [EVALUACION] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EVALUACION] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EVALUACION] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EVALUACION] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EVALUACION] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EVALUACION] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EVALUACION] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EVALUACION] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EVALUACION] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EVALUACION] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EVALUACION] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EVALUACION] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EVALUACION] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EVALUACION] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EVALUACION] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EVALUACION] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EVALUACION] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EVALUACION] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EVALUACION] SET  MULTI_USER 
GO

ALTER DATABASE [EVALUACION] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EVALUACION] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EVALUACION] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EVALUACION] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EVALUACION] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EVALUACION] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EVALUACION] SET  READ_WRITE 
GO

